// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFFgIWfjobENHxaMEsFna9yN2zPhBqVIs',
    appId: '1:191419924732:web:462c9d087ade26340a9779',
    messagingSenderId: '191419924732',
    projectId: 'chap-app-2fcaf',
    authDomain: 'chap-app-2fcaf.firebaseapp.com',
    storageBucket: 'chap-app-2fcaf.appspot.com',
    measurementId: 'G-BLXPSN7JBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8l0f5bvvfKtzWpsjvGLsT-Hmo6WL-1x4',
    appId: '1:191419924732:android:20fbe87a3fe98a300a9779',
    messagingSenderId: '191419924732',
    projectId: 'chap-app-2fcaf',
    storageBucket: 'chap-app-2fcaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBER-bqv4uuaXcuAOcYb9w2QGXh7CDuEOY',
    appId: '1:191419924732:ios:31efe437d95063ff0a9779',
    messagingSenderId: '191419924732',
    projectId: 'chap-app-2fcaf',
    storageBucket: 'chap-app-2fcaf.appspot.com',
    iosClientId: '191419924732-vcbq5h1d2i0vqloh30pqmq95oc9j81l8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBER-bqv4uuaXcuAOcYb9w2QGXh7CDuEOY',
    appId: '1:191419924732:ios:31efe437d95063ff0a9779',
    messagingSenderId: '191419924732',
    projectId: 'chap-app-2fcaf',
    storageBucket: 'chap-app-2fcaf.appspot.com',
    iosClientId: '191419924732-vcbq5h1d2i0vqloh30pqmq95oc9j81l8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
